



teams = {2007: [u'SAS', u'OKC', u'CHI', u'BOS', u'PHO', u'MEM', u'ORL',
                u'NYK', u'PHI', u'NOH', u'UTA', u'ATL', u'DEN', u'IND',
                u'HOU', u'SAC', u'CHA', u'LAL', u'DET', u'BRK', u'MIN',
                u'GSW', u'TOR', u'POR', u'WAS', u'LAC', u'MIA', u'MIL',
                u'CLE', u'DAL'],
         2008: [u'SAS', u'OKC', u'CHI', u'BOS', u'PHO', u'MEM', u'ORL',
                u'NYK', u'PHI', u'NOH', u'UTA', u'ATL', u'DEN', u'IND',
                u'HOU', u'SAC', u'CHA', u'LAL', u'DET', u'BRK', u'MIN',
                u'GSW', u'TOR', u'POR', u'WAS', u'LAC', u'MIA', u'MIL',
                u'CLE', u'DAL'],
         2009: [u'SAS', u'OKC', u'CHI', u'BOS', u'PHO', u'MEM', u'ORL',
                u'NYK', u'PHI', u'NOH', u'UTA', u'ATL', u'DEN', u'IND',
                u'HOU', u'SAC', u'CHA', u'LAL', u'DET', u'BRK', u'MIN',
                u'GSW', u'TOR', u'POR', u'WAS', u'LAC', u'MIA', u'MIL',
                u'CLE', u'DAL'],
         2010: [u'SAS', u'OKC', u'CHI', u'BOS', u'PHO', u'MEM', u'ORL',
                u'NYK', u'PHI', u'NOH', u'UTA', u'ATL', u'DEN', u'IND',
                u'HOU', u'SAC', u'CHA', u'LAL', u'DET', u'BRK', u'MIN',
                u'GSW', u'TOR', u'POR', u'WAS', u'LAC', u'MIA', u'MIL',
                u'CLE', u'DAL'],
         2011: [u'SAS', u'OKC', u'CHI', u'BOS', u'PHO', u'MEM', u'ORL',
                u'NYK', u'PHI', u'NOH', u'UTA', u'ATL', u'DEN', u'IND',
                u'HOU', u'SAC', u'CHA', u'LAL', u'DET', u'BRK', u'MIN',
                u'GSW', u'TOR', u'POR', u'WAS', u'LAC', u'MIA', u'MIL',
                u'CLE', u'DAL'],
         2012: [u'SAS', u'OKC', u'CHI', u'BOS', u'PHO', u'MEM', u'ORL',
                u'NYK', u'PHI', u'NOH', u'UTA', u'ATL', u'DEN', u'IND',
                u'HOU', u'SAC', u'CHA', u'LAL', u'DET', u'BRK', u'MIN',
                u'GSW', u'TOR', u'POR', u'WAS', u'LAC', u'MIA', u'MIL',
                u'CLE', u'DAL'],
         2013: [u'SAS', u'OKC', u'CHI', u'BOS', u'PHO', u'MEM', u'ORL',
                u'NYK', u'PHI', u'NOH', u'UTA', u'ATL', u'DEN', u'IND',
                u'HOU', u'SAC', u'CHA', u'LAL', u'DET', u'BRK', u'MIN',
                u'GSW', u'TOR', u'POR', u'WAS', u'LAC', u'MIA', u'MIL',
                u'CLE', u'DAL'],
         2014: [u'SAS', u'OKC', u'CHI', u'BOS', u'PHO', u'MEM', u'ORL',
                u'NYK', u'PHI', u'NOP', u'UTA', u'ATL', u'DEN', u'IND',
                u'HOU', u'SAC', u'CHA', u'LAL', u'DET', u'BRK', u'MIN',
                u'GSW', u'TOR', u'POR', u'WAS', u'LAC', u'MIA', u'MIL',
                u'CLE', u'DAL'],
         2015: [u'SAS', u'OKC', u'CHI', u'BOS', u'PHO', u'MEM', u'ORL',
                u'NYK', u'PHI', u'NOP', u'UTA', u'ATL', u'DEN', u'IND',
                u'HOU', u'SAC', u'CHO', u'LAL', u'DET', u'BRK', u'MIN',
                u'GSW', u'TOR', u'POR', u'WAS', u'LAC', u'MIA', u'MIL',
                u'CLE', u'DAL']}
